//=============================================================================
//! \file ISM330DHCX.hpp
//!       6-Axis sensor header
//! \author Daniel J. Greenhoe
//=============================================================================


//-----------------------------------------------------------------------------
// !\brief ISM330DHCX Register Definitions
//-----------------------------------------------------------------------------
enum // class ISM330DHCX_Regs
{
  REG_FUNC_CFG_ACCESS           = 0x01,
  REG_PIN_CTRL                  = 0x02,
  REG_FIFO_CTRL1                = 0x07,
  REG_FIFO_CTRL2                = 0x08,
  REG_FIFO_CTRL3                = 0x09,
  REG_FIFO_CTRL4                = 0x0A,
  REG_COUNTER_BDR_REG1          = 0x0B,
  REG_COUNTER_BDR_REG2          = 0x0C,
  REG_INT1_CTRL                 = 0x0D,
  REG_INT2_CTRL                 = 0x0E,
  REG_WHO_AM_I                  = 0x0F,
  REG_CTRL1_XL                  = 0x10,
  REG_CTRL2_G                   = 0x11,
  REG_CTRL3_C                   = 0x12,
  REG_CTRL4_C                   = 0x13,
  REG_CTRL5_C                   = 0x14,
  REG_CTRL6_C                   = 0x15,
  REG_CTRL7_G                   = 0x16,
  REG_CTRL8_XL                  = 0x17,
  REG_CTRL9_XL                  = 0x18,
  REG_CTRL10_C                  = 0x19,
  REG_ALL_INT_SRC               = 0x1A,
  REG_WAKE_UP_SRC               = 0x1B,
  REG_TAP_SRC                   = 0x1C,
  REG_DRD_SRC                   = 0x1D,
  REG_STATUS_REG                = 0x1E,
  REG_STATUS_SPIAux             = 0x1E,
  REG_OUT_TEMP_L                = 0x20,
  REG_OUT_TEMP_H                = 0x21,
  REG_OUTX_L_G                  = 0x22,
  REG_OUTX_H_G                  = 0x23,
  REG_OUTY_L_G                  = 0x24,
  REG_OUTY_H_G                  = 0x25,
  REG_OUTZ_L_G                  = 0x26,
  REG_OUTZ_H_G                  = 0x27,
  REG_OUTX_L_A                  = 0x28,
  REG_OUTX_H_A                  = 0x29,
  REG_OUTY_L_A                  = 0x2A,
  REG_OUTY_H_A                  = 0x2B,
  REG_OUTZ_L_A                  = 0x2C,
  REG_OUTZ_H_A                  = 0x2D,
  REG_EMB_FUNC_STATUS_MAINPAGE  = 0x35,
  REG_FSM_STATUS_A_MAINPAGE     = 0x36,
  REG_FSM_STATUS_B_MAINPAGE     = 0x37,
  REG_MLC_STATUS_MAINPAGE       = 0x38,
  REG_STATUS_MASTER_MAINPAGE    = 0x39,
  REG_FIFO_STATUS1              = 0x3A,
  REG_FIFO_STATUS2              = 0x3B,
  REG_TIMESTAMP0                = 0x40,
  REG_TIMESTAMP1                = 0x41,
  REG_TIMESTAMP2                = 0x42,
  REG_TIMESTAMP3                = 0x43,
  REG_TAP_CFG0                  = 0x56,
  REG_TAP_CFG1                  = 0x57,
  REG_TAP_CFG2                  = 0x58,
  REG_TAP_THS_6D                = 0x59,
  REG_INT_DUR2                  = 0x5A,
  REG_WAKE_UP_THS               = 0x5B,
  REG_WAKE_UP_DUR               = 0x5C,
  REG_FREE_FALL                 = 0x5D,
  REG_MD1_CFG                   = 0x5E,
  REG_MD2_CFG                   = 0x5F,
  REG_INTERNAL_FREQ_FINE        = 0x63,
  REG_INT_OIS                   = 0x6F,
  REG_CTRL1_OIS                 = 0x70,
  REG_CTRL2_OIS                 = 0x71,
  REG_CTRL3_OIS                 = 0x72,
  REG_X_OFS_USR                 = 0x73,
  REG_Y_OFS_USR                 = 0x74,
  REG_Z_OFS_USR                 = 0x75,
  REG_FIFO_DATA_OUT_TAG         = 0x78,
  REG_FIFO_DATA_OUT_X_L         = 0x79,
  REG_FIFO_DATA_OUT_X_H         = 0x7A,
  REG_FIFO_DATA_OUT_Y_L         = 0x7B,
  REG_FIFO_DATA_OUT_Y_H         = 0x7C,
  REG_FIFO_DATA_OUT_Z_L         = 0x7D,
  REG_FIFO_DATA_OUT_Z_H         = 0x7E,
  REG_PAGE_SEL                  = 0x02,
  REG_EMB_FUNC_EN_A             = 0x04,
  REG_EMB_FUNC_EN_B             = 0x05,
  REG_PAGE_ADDRESS              = 0x08,
  REG_PAGE_VALUE                = 0x09,
  REG_EMB_FUNC_INT1             = 0x0A,
  REG_FSM_INT1_A                = 0x0B,
  REG_FSM_INT1_B                = 0x0C,
  REG_MLC_INT1                  = 0x0D,
  REG_EMB_FUNC_INT2             = 0x0E,
  REG_FSM_INT2_A                = 0x0F,
  REG_FSM_INT2_B                = 0x10,
  REG_MLC_INT2                  = 0x11,
  REG_EMB_FUNC_STATUS           = 0x12,
  REG_FSM_STATUS_A              = 0x13,
  REG_FSM_STATUS_B              = 0x14,
  REG_MLC_STATUS                = 0x15,
  REG_PAGE_RW                   = 0x17,
  REG_EMB_FUNC_FIFO_CFG         = 0x44,
  REG_FSM_ENABLE_A              = 0x46,
  REG_FSM_ENABLE_B              = 0x47,
  REG_FSM_LONG_COUNTER_L        = 0x48,
  REG_FSM_LONG_COUNTER_H        = 0x49,
  REG_FSM_LONG_COUNTER_CLEAR    = 0x4A,
  REG_FSM_OUTS1                 = 0x4C,
  REG_FSM_OUTS2                 = 0x4D,
  REG_FSM_OUTS3                 = 0x4E,
  REG_FSM_OUTS4                 = 0x4F,
  REG_FSM_OUTS5                 = 0x50,
  REG_FSM_OUTS6                 = 0x51,
  REG_FSM_OUTS7                 = 0x52,
  REG_FSM_OUTS8                 = 0x53,
  REG_FSM_OUTS9                 = 0x54,
  REG_FSM_OUTS10                = 0x55,
  REG_FSM_OUTS11                = 0x56,
  REG_FSM_OUTS12                = 0x57,
  REG_FSM_OUTS13                = 0x58,
  REG_FSM_OUTS14                = 0x59,
  REG_FSM_OUTS15                = 0x5A,
  REG_FSM_OUTS16                = 0x5B,
  REG_EMB_FUNC_ODR_CFG_B        = 0x5F,
  REG_EMB_FUNC_ODR_CFG_C        = 0x60,
  REG_STEP_COUNTER_L            = 0x62,
  REG_STEP_COUNTER_H            = 0x63,
  REG_EMB_FUNC_SRC              = 0x64,
  REG_EMB_FUNC_INIT_A           = 0x66,
  REG_EMB_FUNC_INIT_B           = 0x67,
  REG_MLC0_SRC                  = 0x70,
  REG_MLC1_SRC                  = 0x71,
  REG_MLC2_SRC                  = 0x72,
  REG_MLC3_SRC                  = 0x73,
  REG_MLC4_SRC                  = 0x74,
  REG_MLC5_SRC                  = 0x75,
  REG_MLC6_SRC                  = 0x76,
  REG_MLC7_SRC                  = 0x77,
  REG_MAG_SENSITIVITY_L         = 0xBA,
  REG_MAG_SENSITIVITY_H         = 0xBB,
  REG_MAG_OFFX_L                = 0xC0,
  REG_MAG_OFFX_H                = 0xC1,
  REG_MAG_OFFY_L                = 0xC2,
  REG_MAG_OFFY_H                = 0xC3,
  REG_MAG_OFFZ_L                = 0xC4,
  REG_MAG_OFFZ_H                = 0xC5,
  REG_MAG_SI_XX_L               = 0xC6,
  REG_MAG_SI_XX_H               = 0xC7,
  REG_MAG_SI_XY_L               = 0xC8,
  REG_MAG_SI_XY_H               = 0xC9,
  REG_MAG_SI_XZ_L               = 0xCA,
  REG_MAG_SI_XZ_H               = 0xCB,
  REG_MAG_SI_YY_L               = 0xCC,
  REG_MAG_SI_YY_H               = 0xCD,
  REG_MAG_SI_YZ_L               = 0xCE,
  REG_MAG_SI_YZ_H               = 0xCF,
  REG_MAG_SI_ZZ_L               = 0xD0,
  REG_MAG_SI_ZZ_H               = 0xD1,
  REG_MAG_CFG_A                 = 0xD4,
  REG_MAG_CFG_B                 = 0xD5,
  REG_FSM_LC_TIMEOUT_L          = 0x7A,
  REG_FSM_LC_TIMEOUT_H          = 0x7B,
  REG_FSM_PROGRAMS              = 0x7C,
  REG_FSM_START_ADD_L           = 0x7E,
  REG_FSM_START_ADD_H           = 0x7F,
  REG_PEDO_CMD_REG              = 0x83,
  REG_PEDO_DEB_CONF             = 0x84,
  REG_PEDO_SC_DELTAT_L          = 0xD0,
  REG_PEDO_SC_DELTAT_H          = 0xD1,
  REG_MLC_MAG_SENSITIVITY_L     = 0xE8,
  REG_MLC_MAG_SENSITIVITY_H     = 0xE9,
  REG_SENSOR_HUB_1              = 0x02,
  REG_SENSOR_HUB_2              = 0x03,
  REG_SENSOR_HUB_3              = 0x04,
  REG_SENSOR_HUB_4              = 0x05,
  REG_SENSOR_HUB_5              = 0x06,
  REG_SENSOR_HUB_6              = 0x07,
  REG_SENSOR_HUB_7              = 0x08,
  REG_SENSOR_HUB_8              = 0x09,
  REG_SENSOR_HUB_9              = 0x0A,
  REG_SENSOR_HUB_10             = 0x0B,
  REG_SENSOR_HUB_11             = 0x0C,
  REG_SENSOR_HUB_12             = 0x0D,
  REG_SENSOR_HUB_13             = 0x0E,
  REG_SENSOR_HUB_14             = 0x0F,
  REG_SENSOR_HUB_15             = 0x10,
  REG_SENSOR_HUB_16             = 0x11,
  REG_SENSOR_HUB_17             = 0x12,
  REG_SENSOR_HUB_18             = 0x13,
  REG_MASTER_CONFIG             = 0x14,
  REG_SLV0_ADD                  = 0x15,
  REG_SLV0_SUBADD               = 0x16,
  REG_SLAVE0_CONFIG             = 0x17,
  REG_SLV1_ADD                  = 0x18,
  REG_SLV1_SUBADD               = 0x19,
  REG_SLAVE1_CONFIG             = 0x1A,
  REG_SLV2_ADD                  = 0x1B,
  REG_SLV2_SUBADD               = 0x1C,
  REG_SLAVE2_CONFIG             = 0x1D,
  REG_SLV3_ADD                  = 0x1E,
  REG_SLV3_SUBADD               = 0x1F,
  REG_SLAVE3_CONFIG             = 0x20,
  REG_DATAWRITE_SLV0            = 0x21,
  REG_STATUS_MASTER             = 0x22
};

enum
{
  BIT_FUNC_CFG_ACCESS = 0x01 << 7,
  BIT_SHUB_REG_ACCESS = 0x01 << 6
};

//-----------------------------------------------------------------------------
// !\brief ISM330DHCX Class Definition
//-----------------------------------------------------------------------------
class ISM330DHCX : public spi
{
  private:
  public:
    HAL_StatusTypeDef ReadOneByte( uint8_t const Register, uint8_t* RegVal );
    HAL_StatusTypeDef WriteOneByte( uint8_t const Register, uint8_t RegVal );
    HAL_StatusTypeDef ReadNBytes( uint8_t const Register, uint8_t const NumBytes, uint8_t* RegBuf );
    HAL_StatusTypeDef Init(void);
    HAL_StatusTypeDef SoftReset( void );
    HAL_StatusTypeDef GetChipID( uint8_t* ChipID );
    HAL_StatusTypeDef ReadTemp( uint8_t* Temp );
};
